GET http://localhost:3000/alive
###

PUT http://localhost:3000/catalog
Content-Type: application/json

{"_id": 1, "firstName": "Vasya", "lastName": "Pupkin", "phone": "8-(999)-123-00-01"}
###

PUT http://localhost:3000/catalog
Content-Type: application/json

{"_id": 2, "firstName": "Kostya", "lastName": "Vorobiev", "phone": "8-(999)-123-00-02"}
###

PUT http://localhost:3000/catalog
Content-Type: application/json

{"_id": 3, "firstName": "Katya", "lastName": "Kotova", "phone": "8-(999)-123-00-03"}
###